version: "3"
services:
  app:
    build: ./
    restart: always
    ports:
      - 8080:8080
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
      APP_ENV: $APP_ENV
      DATABASE_USERNAME: rhuser
      DATABASE_PASSWORD: rhpass
      DATABASE_JDBC_URL: jdbc:postgresql://db:5432/refactorhub
      DATABASE_DRIVER: org.postgresql.Driver
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: refactorhub
      POSTGRES_USER: rhuser
      POSTGRES_PASSWORD: rhpass