version: "3"
services:
  frontend:
    build: 
      context: ./ 
      dockerfile: client/Dockerfile
    restart: always
    ports:
      - 3000:3000
  backend:
    build: ./
    restart: always
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
      APP_ENV: ${APP_ENV:-}
      LOG_ACTION: ${LOG_ACTION:-}
      DATABASE_URL: postgres://rhuser:rhpass@db:5432/refactorhub
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: refactorhub
      POSTGRES_USER: rhuser
      POSTGRES_PASSWORD: rhpass
    volumes:
      - refactorhub_volume:/var/lib/postgresql/data

volumes:
  refactorhub_volume:
    driver: local