spring:
  jpa:
    open-in-view: false
  profiles:
    active: dev
security:
  oauth2:
    client:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
      scope: read:user
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false